# Generated by Django 3.0.3 on 2020-03-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(default=0)),
                ('Product_ID', models.CharField(choices=[('P0069042', 'P00069042'), ('P00248942', 'P00248942'), ('P00087842', 'P00087842'), ('P00085442', 'P00085442')], max_length=15)),
                ('Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=15)),
                ('Age', models.CharField(choices=[('0-17', '0-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-50', '46-50'), ('51-55', '51-55'), ('55+', '55+')], max_length=15)),
                ('Occupation', models.IntegerField(default=0)),
                ('City_Category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=15)),
                ('Stay_In_Current_City_Years', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=15)),
                ('Marital_Status', models.IntegerField(default=0)),
                ('Product_Category_1', models.FloatField(default=0)),
                ('Product_Category_2', models.FloatField(default=0)),
                ('Product_Category_3', models.IntegerField(default=0)),
            ],
        ),
    ]
